version: '3.7'

services:
  currency-exchange-api:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    image: currency-exchange-api:latest
    container_name: currency-exchange-api
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/src/:/app/src
    ports: 
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres-db-dev
  
  postgres-db-dev:
    image: postgres:latest
    container_name: postgres-db-dev
    env_file:
      - .env
    ports:
      - 5432:5432

